package com.lidchanin.crudindiploma.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lidchanin.crudindiploma.database.ShoppingList;
import com.lidchanin.crudindiploma.database.ExistingProduct;
import com.lidchanin.crudindiploma.database.Product;

import com.lidchanin.crudindiploma.database.ShoppingListDao;
import com.lidchanin.crudindiploma.database.ExistingProductDao;
import com.lidchanin.crudindiploma.database.ProductDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shoppingListDaoConfig;
    private final DaoConfig existingProductDaoConfig;
    private final DaoConfig productDaoConfig;

    private final ShoppingListDao shoppingListDao;
    private final ExistingProductDao existingProductDao;
    private final ProductDao productDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shoppingListDaoConfig = daoConfigMap.get(ShoppingListDao.class).clone();
        shoppingListDaoConfig.initIdentityScope(type);

        existingProductDaoConfig = daoConfigMap.get(ExistingProductDao.class).clone();
        existingProductDaoConfig.initIdentityScope(type);

        productDaoConfig = daoConfigMap.get(ProductDao.class).clone();
        productDaoConfig.initIdentityScope(type);

        shoppingListDao = new ShoppingListDao(shoppingListDaoConfig, this);
        existingProductDao = new ExistingProductDao(existingProductDaoConfig, this);
        productDao = new ProductDao(productDaoConfig, this);

        registerDao(ShoppingList.class, shoppingListDao);
        registerDao(ExistingProduct.class, existingProductDao);
        registerDao(Product.class, productDao);
    }
    
    public void clear() {
        shoppingListDaoConfig.clearIdentityScope();
        existingProductDaoConfig.clearIdentityScope();
        productDaoConfig.clearIdentityScope();
    }

    public ShoppingListDao getShoppingListDao() {
        return shoppingListDao;
    }

    public ExistingProductDao getExistingProductDao() {
        return existingProductDao;
    }

    public ProductDao getProductDao() {
        return productDao;
    }

}
