package com.lidchanin.crudindiploma.database;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "EXISTING_PRODUCT".
*/
public class ExistingProductDao extends AbstractDao<ExistingProduct, Long> {

    public static final String TABLENAME = "EXISTING_PRODUCT";

    /**
     * Properties of entity ExistingProduct.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Quantity = new Property(1, Double.class, "quantity", false, "QUANTITY");
        public final static Property Unit = new Property(2, Boolean.class, "unit", false, "UNIT");
        public final static Property IsPurchased = new Property(3, Boolean.class, "isPurchased", false, "IS_PURCHASED");
        public final static Property ProductId = new Property(4, Long.class, "productId", false, "PRODUCT_ID");
        public final static Property ShoppingListId = new Property(5, long.class, "shoppingListId", false, "SHOPPING_LIST_ID");
    }

    private DaoSession daoSession;

    private Query<ExistingProduct> shoppingList_ExistingProductsQuery;

    public ExistingProductDao(DaoConfig config) {
        super(config);
    }
    
    public ExistingProductDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"EXISTING_PRODUCT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"QUANTITY\" REAL," + // 1: quantity
                "\"UNIT\" INTEGER," + // 2: unit
                "\"IS_PURCHASED\" INTEGER," + // 3: isPurchased
                "\"PRODUCT_ID\" INTEGER," + // 4: productId
                "\"SHOPPING_LIST_ID\" INTEGER NOT NULL );"); // 5: shoppingListId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"EXISTING_PRODUCT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ExistingProduct entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Double quantity = entity.getQuantity();
        if (quantity != null) {
            stmt.bindDouble(2, quantity);
        }
 
        Boolean unit = entity.getUnit();
        if (unit != null) {
            stmt.bindLong(3, unit ? 1L: 0L);
        }
 
        Boolean isPurchased = entity.getIsPurchased();
        if (isPurchased != null) {
            stmt.bindLong(4, isPurchased ? 1L: 0L);
        }
 
        Long productId = entity.getProductId();
        if (productId != null) {
            stmt.bindLong(5, productId);
        }
        stmt.bindLong(6, entity.getShoppingListId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ExistingProduct entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Double quantity = entity.getQuantity();
        if (quantity != null) {
            stmt.bindDouble(2, quantity);
        }
 
        Boolean unit = entity.getUnit();
        if (unit != null) {
            stmt.bindLong(3, unit ? 1L: 0L);
        }
 
        Boolean isPurchased = entity.getIsPurchased();
        if (isPurchased != null) {
            stmt.bindLong(4, isPurchased ? 1L: 0L);
        }
 
        Long productId = entity.getProductId();
        if (productId != null) {
            stmt.bindLong(5, productId);
        }
        stmt.bindLong(6, entity.getShoppingListId());
    }

    @Override
    protected final void attachEntity(ExistingProduct entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ExistingProduct readEntity(Cursor cursor, int offset) {
        ExistingProduct entity = new ExistingProduct( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getDouble(offset + 1), // quantity
            cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2) != 0, // unit
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0, // isPurchased
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // productId
            cursor.getLong(offset + 5) // shoppingListId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ExistingProduct entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setQuantity(cursor.isNull(offset + 1) ? null : cursor.getDouble(offset + 1));
        entity.setUnit(cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2) != 0);
        entity.setIsPurchased(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
        entity.setProductId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setShoppingListId(cursor.getLong(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ExistingProduct entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ExistingProduct entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ExistingProduct entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "existingProducts" to-many relationship of ShoppingList. */
    public List<ExistingProduct> _queryShoppingList_ExistingProducts(long shoppingListId) {
        synchronized (this) {
            if (shoppingList_ExistingProductsQuery == null) {
                QueryBuilder<ExistingProduct> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ShoppingListId.eq(null));
                shoppingList_ExistingProductsQuery = queryBuilder.build();
            }
        }
        Query<ExistingProduct> query = shoppingList_ExistingProductsQuery.forCurrentThread();
        query.setParameter(0, shoppingListId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getProductDao().getAllColumns());
            builder.append(" FROM EXISTING_PRODUCT T");
            builder.append(" LEFT JOIN PRODUCT T0 ON T.\"PRODUCT_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected ExistingProduct loadCurrentDeep(Cursor cursor, boolean lock) {
        ExistingProduct entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Product product = loadCurrentOther(daoSession.getProductDao(), cursor, offset);
        entity.setProduct(product);

        return entity;    
    }

    public ExistingProduct loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<ExistingProduct> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<ExistingProduct> list = new ArrayList<ExistingProduct>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<ExistingProduct> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<ExistingProduct> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
