package com.lidchanin.crudindiploma.database;

import org.greenrobot.greendao.annotation.*;

import java.util.List;
import com.lidchanin.crudindiploma.database.DaoSession;
import org.greenrobot.greendao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "SHOPPING_LIST".
 */
@Entity(active = true)
public class ShoppingList {

    @Id
    private Long id;

    @NotNull
    private String name;

    @NotNull
    private String date;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient ShoppingListDao myDao;

    @ToMany(joinProperties = {
        @JoinProperty(name = "id", referencedName = "shoppingListId")
    })
    private List<ExistingProduct> existingProducts;

    @Generated
    public ShoppingList() {
    }

    public ShoppingList(Long id) {
        this.id = id;
    }

    @Generated
    public ShoppingList(Long id, String name, String date) {
        this.id = id;
        this.name = name;
        this.date = date;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getShoppingListDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(@NotNull String name) {
        this.name = name;
    }

    @NotNull
    public String getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(@NotNull String date) {
        this.date = date;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    @Generated
    public List<ExistingProduct> getExistingProducts() {
        if (existingProducts == null) {
            __throwIfDetached();
            ExistingProductDao targetDao = daoSession.getExistingProductDao();
            List<ExistingProduct> existingProductsNew = targetDao._queryShoppingList_ExistingProducts(id);
            synchronized (this) {
                if(existingProducts == null) {
                    existingProducts = existingProductsNew;
                }
            }
        }
        return existingProducts;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    @Generated
    public synchronized void resetExistingProducts() {
        existingProducts = null;
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

}
