package com.lidchanin.shoppinglist.database;

import org.greenrobot.greendao.annotation.*;

import java.util.List;
import com.lidchanin.shoppinglist.database.dao.DaoSession;
import org.greenrobot.greendao.DaoException;

import com.lidchanin.shoppinglist.database.dao.ShoppingListDao;
import com.lidchanin.shoppinglist.database.dao.UsedProductDao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "SHOPPING_LIST".
 */
@Entity(active = true)
public class ShoppingList {

    /* id */
    @Id
    private Long id;

    /* shopping list name */
    @NotNull
    private String name;
    /* date of creation */
    private long date;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient ShoppingListDao myDao;

    @ToMany(joinProperties = {
        @JoinProperty(name = "id", referencedName = "shoppingListId")
    })
    private List<UsedProduct> usedProducts;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public ShoppingList() {
    }

    public ShoppingList(Long id) {
        this.id = id;
    }

    @Generated
    public ShoppingList(Long id, String name, long date) {
        this.id = id;
        this.name = name;
        this.date = date;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getShoppingListDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(@NotNull String name) {
        this.name = name;
    }

    public long getDate() {
        return date;
    }

    public void setDate(long date) {
        this.date = date;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    @Generated
    public List<UsedProduct> getUsedProducts() {
        if (usedProducts == null) {
            __throwIfDetached();
            UsedProductDao targetDao = daoSession.getUsedProductDao();
            List<UsedProduct> usedProductsNew = targetDao._queryShoppingList_UsedProducts(id);
            synchronized (this) {
                if(usedProducts == null) {
                    usedProducts = usedProductsNew;
                }
            }
        }
        return usedProducts;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    @Generated
    public synchronized void resetUsedProducts() {
        usedProducts = null;
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
