package com.lidchanin.shoppinglist.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "STATISTIC".
 */
@Entity
public class Statistic {

    /* id */
    @Id
    private Long id;

    /* product name */
    @NotNull
    private String name;
    /* used product quantity */
    private double quantity;
    /* product cost * used product quantity * product cost */
    private double totalCost;
    /* true -> kg, false -> pieces */
    private boolean unit;
    /* date when the product in the shopping list was marked as purchased */
    private long date;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Statistic() {
    }

    public Statistic(Long id) {
        this.id = id;
    }

    @Generated
    public Statistic(Long id, String name, double quantity, double totalCost, boolean unit, long date) {
        this.id = id;
        this.name = name;
        this.quantity = quantity;
        this.totalCost = totalCost;
        this.unit = unit;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(@NotNull String name) {
        this.name = name;
    }

    public double getQuantity() {
        return quantity;
    }

    public void setQuantity(double quantity) {
        this.quantity = quantity;
    }

    public double getTotalCost() {
        return totalCost;
    }

    public void setTotalCost(double totalCost) {
        this.totalCost = totalCost;
    }

    public boolean getUnit() {
        return unit;
    }

    public void setUnit(boolean unit) {
        this.unit = unit;
    }

    public long getDate() {
        return date;
    }

    public void setDate(long date) {
        this.date = date;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
