package com.lidchanin.crudindiploma.database.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lidchanin.crudindiploma.database.ShoppingList;
import com.lidchanin.crudindiploma.database.Product;
import com.lidchanin.crudindiploma.database.UsedProduct;

import com.lidchanin.crudindiploma.database.dao.ShoppingListDao;
import com.lidchanin.crudindiploma.database.dao.ProductDao;
import com.lidchanin.crudindiploma.database.dao.UsedProductDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shoppingListDaoConfig;
    private final DaoConfig productDaoConfig;
    private final DaoConfig usedProductDaoConfig;

    private final ShoppingListDao shoppingListDao;
    private final ProductDao productDao;
    private final UsedProductDao usedProductDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shoppingListDaoConfig = daoConfigMap.get(ShoppingListDao.class).clone();
        shoppingListDaoConfig.initIdentityScope(type);

        productDaoConfig = daoConfigMap.get(ProductDao.class).clone();
        productDaoConfig.initIdentityScope(type);

        usedProductDaoConfig = daoConfigMap.get(UsedProductDao.class).clone();
        usedProductDaoConfig.initIdentityScope(type);

        shoppingListDao = new ShoppingListDao(shoppingListDaoConfig, this);
        productDao = new ProductDao(productDaoConfig, this);
        usedProductDao = new UsedProductDao(usedProductDaoConfig, this);

        registerDao(ShoppingList.class, shoppingListDao);
        registerDao(Product.class, productDao);
        registerDao(UsedProduct.class, usedProductDao);
    }
    
    public void clear() {
        shoppingListDaoConfig.clearIdentityScope();
        productDaoConfig.clearIdentityScope();
        usedProductDaoConfig.clearIdentityScope();
    }

    public ShoppingListDao getShoppingListDao() {
        return shoppingListDao;
    }

    public ProductDao getProductDao() {
        return productDao;
    }

    public UsedProductDao getUsedProductDao() {
        return usedProductDao;
    }

}
